[package]
name = "server"
version = "0.1.0"
authors = ["Oliver Bøving <oliverboving@gmail.com>"]

[dependencies]
actix-web = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
syn = {version="0.14",features=["full"]}
quote = "*"
